[FEAT]: 카테고리 필터링 기능 추가
SYSONE-PICKME/PICKME pull request #124
Opened 2024-09-21 08:09 UTC by kys0411

## 🍀이슈 번호
- closes #123 

## ✅ 구현 내용
- [ ] 카테고리 필터링 기능 쿼리 추가

## 🐸고민사항 & 기타
카테고리 목록에 전체보기 같은것도 추가하는게 좋을까여? 카테고리 하나 버튼 누르면 전체조회로 돌아올 방법이 없어서유

2024-09-21 09:10 UTC, Yang-soeun requested changes
👍👍👍

2024-09-21 12:09 UTC, nyeongha approved these changes
LGTM👍👍

2024-09-21 13:49 UTC, Sohottoday approved these changes
지속적인 고민과 아이디어 Good!

2024-09-22 09:01 UTC, nyeongha approved these changes

2024-09-22 10:10 UTC, Yang-soeun approved these changes
그러게용! 그럼 전체보기로 돌아가는거 하나 있으면 좋을것 같아용

2024-09-22 10:21 UTC, merged