[FEAT]: 관리자 공지 및 캠페인 관리 페이지
SYSONE-PICKME/PICKME pull request #129
Opened 2024-09-21 11:32 UTC by Sohottoday

## 🍀이슈 번호 (이슈 번호를 작성해주세요)
- closes #128 

## ✅ 구현 내용
- [ ] 관리자 공지 및 캠페인  목록 구현
- [ ] 관리자 공지 및 캠페인 작성 구현
- [ ] 관리자 공지 및 캠페인 수정, 삭제 구현

## 🐸고민사항 & 기타
- 이전 이슈 16번에서 이어진 파일들이며 Github 분기 이슈로 인해 새로 만들어진 이슈 및 PR입니다.

- 이전 PR에서 수정된 부분
   > 작성자가 아니면 수정/삭제 버튼이 출력되지 않도록 수정하였습니다.
   > type을 String에서 enum으로 수정하였습니다.

- 이전 PR 기준 미구현된 부분
   > updateCampaign의 `campaignService.updateCampaign(campaignDto, id);` 로 구현 조언에 대한 부분
   > AJAX 구현

2024-09-21 14:54 UTC, Yang-soeun requested changes
수고하셨습니당 ~~👍👍👍👍👍

@CurrentUser 서비스 안에서 사용한 부분이랑 xml쪽, 그리고 restController 분리는 꼭해주세용!!

그리고 코드 내부분이 id로 select를 하는데 select한 결과가 존재하지 않는 경우에 대한 예외 처리가 부족한거 같아용

그리고 수정, 삭제 시에는 동일한 세관인지 확인하는 부분이 추가되면 더욱 더 안전한 서비스가 되지 않을까아~~~(?)

2024-09-21 14:54 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/CampaignController.java
> +		model.addAttribute("customsId",customs.getId());
포맷터가 적용 안된것 같은데여?🍒🍒🍒🍒🍒

customsId는 어디에서 사용하나요?

2024-09-21 14:54 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/CampaignController.java
> +	public ResponseEntity<String> deleteCampaign(@PathVariable("id") Long id) {
이거는 비동기 같은데 비동기는 RestController 따로 만들어주셔야 합니당

2024-09-21 14:54 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/CampaignController.java
> +			return ResponseEntity.ok("삭제 성공");
그리고 현재 구현되어 있는 BaseReponse를 사용해주세용

2024-09-21 14:54 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +	public ResponseEntity<String> deleteNotice(@PathVariable("id") Long id) {
여기도 비동기

2024-09-21 14:54 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/domain/Notice.java
> +	public enum NoticeType {
저희 enum은 constant 패키지 안에 넣어서 관리하고 있습니당 이것도 그렇게 해주시면 좋을것 같아용

2024-09-21 14:54 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +	public Long createCampaign(CampaignDto campaignDto, @CurrentUser Customs customs) throws IOException {
@CurrentUser Customs customs 컨트롤러에서 넘겨주고 있는데 어노테이션을 한번 더 붙인 이유는????

🍒🍒🍒

2024-09-21 14:54 UTC, Yang-soeun commented on pickme/src/main/resources/mapper/NoticeMapper.xml
> +        ON
🍒🍒🍒🍒

2024-09-21 14:54 UTC, Yang-soeun commented on pickme/src/main/resources/mapper/NoticeMapper.xml
> +        ON
🍒🍒🍒🍒

2024-09-21 14:54 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +	public List<CampaignDto> getAllCampaigns() {
본인이 작성한 것만 조회하도록 하기로 한거 아니였나용?

2024-09-21 14:54 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +	public void updateCampaign(CampaignDto campaignDto, @CurrentUser Customs customs) throws IOException {
여기도 @CurrentUser 🍒🍒🍒

2024-09-21 14:54 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/NoticeService.java
> +			.collect(Collectors.toList());
toList()

2024-09-21 14:54 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/NoticeService.java
> +	public void updateNotice(NoticeDto noticeDto, @CurrentUser Customs customs) {
@CurrentUser 🍒🍒🍒🍒

2024-09-21 14:54 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +		noticeDto = noticeDto.withId(id);
계속 이렇게 하고 싶으시면 차라리 setter를 사용하는게 더 효율적일듯 합니당

2024-09-21 14:54 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/CampaignController.java
전체적으로 customsId를 넘겨주고 있는데 어떤 동작을 위해 필요한가용????

2024-09-21 14:54 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/dto/CampaignDto.java
> +	public CampaignDto withId(Long id) {
setter를 선언하셨는데 굳이 setter를 안쓰시고 다시 빌드하는 이유가 궁금합니다

2024-09-21 14:54 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/CampaignController.java
> +	@PostMapping("/edit/{id}")
수정하는건 비동기로 하는게 더 좋을것 같은데용!

2024-09-21 14:54 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +		Notice existingCampaign = noticeMapper.selectById(campaignDto.getId());
existingCampaign 앞에 굳이 existing 안붙여도 될거 같아요 그냥 campaign, notice를 사용하시는게 오히려 가독성에 더 좋을것 같은뎅... 저의 생각입니다!

2024-09-21 14:54 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +		deleteExistingImage(existingCampaign);
이런 부분도 그냥 deleteImage 이런게 저는 더 좋을것 같긴해여

2024-09-21 14:54 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +
이 부분은 업데이트랑, 생성하는 부분에서 둘 다 이 메소드를 사용하려고 조건을 많이 추가한 느낌이랄까....

생성하는 경우에는 당연히 존재하는 이미지는 없고 s3에 올라간 이미지도 없을텐뎅.. 
```
		if (existingCampaign != null && Notice.NoticeType.CAMPAIGN.equals(existingCampaign.getType())) {
			return existingCampaign.getContent();
		}
```

이 부분도 생성하는 경우라면 필요없는 부분인데 메소드 하나로 같이 쓰려고 하다보니 더 복잡해진 느낌이랄까~ 차라리 그냥 메소드로 분리 안하는게 더 좋을것 같다는 생각도 들어용

2024-09-21 14:54 UTC, Yang-soeun commented on pickme/src/main/resources/mapper/NoticeMapper.xml
전체적으로 sql문 마지막에 세미콜론이 있는데 ~~~ 제거해주세용 🍒🍒

2024-09-22 03:39 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/controller/CampaignController.java
> +	public ResponseEntity<String> deleteCampaign(@PathVariable("id") Long id) {
그리고 별건 아니지만 DeleteMapping이랑 Responsebody랑 순서 바꿔주시면 좋을것같아요~

2024-09-22 09:07 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +
이 부분은 예전에 소은님이 리뷰 주신 내용을 통해 알게된 방어적 프로그래밍? 에 대한 글을 읽었을 때 딱 이부분을 작성중이었는데 그래서 최대한의 변수들을 다 가져다 붙였다고 보시면 됩니다!
우선 제약조건을 줄여서 수정해보았습니다!

2024-09-22 09:07 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/controller/CampaignController.java
Id를 통해 수정/삭제버튼 활성화/비활성화 입니다!

2024-09-22 09:07 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/controller/CampaignController.java
> +		model.addAttribute("customsId",customs.getId());
포맷터의 경우 저장되면서 뿅 하고 자동으로 적용되는 줄 알았습니다!
수정 완료!

2024-09-22 14:16 UTC, Sohottoday reviewed
noticeCreate 제외 ajax 도전해보았습니다. 파일이 많이 변하니 기존 댓글들이 Files changed에는 보이지가 않네요 ㅠㅠ

2024-09-22 14:17 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +	public ResponseEntity<String> deleteNotice(@PathVariable("id") Long id) {
수정해보았습니다!

2024-09-22 14:17 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/controller/CampaignController.java
> +	@PostMapping("/edit/{id}")
수정해보았습니다!

2024-09-22 14:17 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/controller/CampaignController.java
> +	public ResponseEntity<String> deleteCampaign(@PathVariable("id") Long id) {
수정해보았습니다!

2024-09-22 23:38 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/dto/NoticeDto.java
> +@Builder
ㅇㅅㅇ

2024-09-22 23:40 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/dto/NoticeDto.java
> +	}
제가 이거 몇번 말씀드렸는데,, dto 안에서 이걸 다 할 필요가 있을까요

2024-09-22 23:44 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +}
1. 메서드 이름 UploadImage도 아니고 processImageUpload는 무슨뜻인가용?
2. if문 너무 많은것같아요 메서드로 따로 빼도 될 것 같아요
3. if문 안에 조건도 가독성이 너무 떨어져용
4. return null..은 왜 해주는 건가용?

2024-09-22 23:47 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/repository/NoticeMapper.java
> +	List<Notice> selectAllCampaigns();
매퍼도 나눠주시면 좋을 것 같아요..

2024-09-22 23:48 UTC, kys0411 requested changes
👍🏻👍🏻

2024-09-23 02:46 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +}
1. 변수명 정하는게 css보다 더 어렵습니다.
2. if문 줄이기 완료
3. 약간의 개선
4. 예상되지 못한 행동했을 경우 널이나 먹어라

2024-09-23 06:01 UTC, Yang-soeun requested changes

2024-09-24 00:55 UTC, Yang-soeun requested changes

2024-09-24 00:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/CampaignController.java
> +		if (campaign == null) {
⭐

2024-09-24 00:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/constant/NoticeType.java
👍👍

2024-09-24 00:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/CampaignRestController.java
> +		@CurrentUser Customs customs) throws IOException {
이런거는 한줄이 더 이쁠것 같아용

2024-09-24 00:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/CampaignRestController.java
나중에 RestController에는 Javadoc 주석 추가해주세용

2024-09-24 00:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeRestController.java
> +
🍒

2024-09-24 00:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeRestController.java
> +	@PutMapping("/create")
PutMapping인데 create는 어색한거 같은데용? ⭐

2024-09-24 00:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +		return customsMapper.findByCustomsId(customsId).orElseThrow(() -> new BusinessException(NOT_FOUND_CUSTOMS));	//todo: notice에서도 똑같이 사용되니 추후 수정
이 todo는 어떤걸 의미하는거죠???

2024-09-24 00:55 UTC, Yang-soeun commented on pickme/src/main/resources/mapper/NoticeMapper.xml
> +            c.id AS customs_customs_id,
🍒🍒🍒🍒🍒🍒🍒🍒🍒

2024-09-24 00:55 UTC, Yang-soeun commented on pickme/src/main/resources/mapper/NoticeMapper.xml
> +            c.id AS customs_customs_id,
🍒🍒🍒🍒🍒🍒🍒🍒

2024-09-24 00:55 UTC, Yang-soeun commented on pickme/src/main/resources/mapper/NoticeMapper.xml
> +            c.role,
role은 왜 필요한거죠???

2024-09-24 00:55 UTC, Yang-soeun commented on pickme/src/main/resources/mapper/NoticeMapper.xml
> +            c.role,
❔❓

2024-09-24 00:55 UTC, Yang-soeun commented on pickme/src/main/resources/mapper/NoticeMapper.xml
> +        values (#{customs.id}, #{title}, #{content}, #{type});
🍒🍒🍒🍒🍒🍒🍒🍒🍒🍒

2024-09-24 00:55 UTC, Yang-soeun commented on pickme/src/main/resources/static/js/notice/campaignList.js
> +//axios에 대해 알아본 결과 RESTful하게 구현하려면 controller에 @Delete로 매핑한 뒤 .get이 아닌 .delete로 구현하는게 더 좋다고 기재되어 있음.
⭐

2024-09-24 01:52 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/controller/CampaignRestController.java
> +		@CurrentUser Customs customs) throws IOException {
수정완료!

2024-09-24 01:52 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/controller/NoticeRestController.java
> +
🙈🙈

2024-09-24 01:52 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +		return customsMapper.findByCustomsId(customsId).orElseThrow(() -> new BusinessException(NOT_FOUND_CUSTOMS));	//todo: notice에서도 똑같이 사용되니 추후 수정
반복해서 사용하고 있어서 고쳐질까 했는데 어렵다고 하여 todo 삭제하였습니다!

2024-09-24 01:52 UTC, Sohottoday commented on pickme/src/main/resources/mapper/NoticeMapper.xml
> +            c.id AS customs_customs_id,
😢😢

2024-09-24 01:52 UTC, Sohottoday commented on pickme/src/main/resources/mapper/NoticeMapper.xml
> +            c.role,
삭제완료!

2024-09-24 01:52 UTC, Sohottoday commented on pickme/src/main/resources/mapper/NoticeMapper.xml
> +            c.id AS customs_customs_id,
🤐🤐

2024-09-24 01:52 UTC, Sohottoday commented on pickme/src/main/resources/mapper/NoticeMapper.xml
> +            c.role,
🤐🤐🤐🐸🐸

2024-09-24 01:52 UTC, Sohottoday commented on pickme/src/main/resources/static/js/notice/campaignList.js
> +//axios에 대해 알아본 결과 RESTful하게 구현하려면 controller에 @Delete로 매핑한 뒤 .get이 아닌 .delete로 구현하는게 더 좋다고 기재되어 있음.
🙈🙈

2024-09-24 01:52 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/controller/CampaignRestController.java
우선 도전 완료!

2024-09-24 01:52 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/controller/CampaignController.java
> +		if (campaign == null) {
🙈🙈🙈

2024-09-24 07:09 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/dto/CampaignDto.java
> +
공백

2024-09-24 07:09 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/dto/NoticeDto.java
> +
여백의미?

2024-09-24 08:19 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +		noticeMapper.delete(id);
deleteById가 낫지 않을까요?

2024-09-24 08:25 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +			return s3Service.uploadImage(campaignDto.getImageFile());
코드 중복인것같아요~

2024-09-24 12:50 UTC, kys0411 commented on pickme/src/main/resources/mapper/NoticeMapper.xml
> +            c.id AS c_id,
🍒

2024-09-24 12:51 UTC, kys0411 commented on pickme/src/main/resources/mapper/NoticeMapper.xml
> +            c.id AS c_id,
🍒

2024-09-24 12:52 UTC, kys0411 approved these changes
👏🏻👏🏻👏🏻

2024-09-25 01:36 UTC, Yang-soeun approved these changes
수고하셨습니당~

2024-09-25 01:36 UTC, merged