[FEAT]: 배송 정보 수정 기능 구현
SYSONE-PICKME/PICKME pull request #131
Opened 2024-09-21 18:54 UTC by nyeongha

## 🍀이슈 번호 (이슈 번호를 작성해주세요)
- closes #61

## ✅ 구현 내용
- [ ] 배송 수정 기능 구현

## 🐸고민사항 & 기타

2024-09-22 15:36 UTC, Sohottoday reviewed
고생하셨습니다!

2024-09-22 15:36 UTC, Sohottoday commented on pickme/src/main/resources/mapper/ItemLawMapper.xml
> +        where Item_id = #{id}
IIII

2024-09-22 15:36 UTC, Sohottoday commented on pickme/src/main/resources/templates/item/editItem.html
> +        function setMinAuctionStartTime() {
여기부터 js부분을 따로 안빼고 여기에 구현하신 이유가 있을까요??

2024-09-22 23:09 UTC, nyeongha commented on pickme/src/main/resources/templates/item/editItem.html
> +        function setMinAuctionStartTime() {
..분리하니까 실행이안돼서 붙여놨어용 다시 시도해볼게요!!

2024-09-23 05:28 UTC, Yang-soeun requested changes

2024-09-23 05:28 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/delivery/controller/CustomsDeliveryController.java
>  	public String saveInvoiceNumber(@RequestBody DeliveryFormDto deliveryFormDto) {
이거는 비동기로 동작하고 있는거 아닌가여??????

2024-09-23 05:28 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/delivery/controller/CustomsDeliveryController.java
> +		model.addAttribute("carrier", deliveryService.getCarrier(itemId));
이거는 저번에 수정한걸로 변경 해주세용~~

2024-09-23 05:28 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/delivery/controller/UserDeliveryController.java
> +		model.addAttribute("carrier", deliveryService.getCarrier(itemId));
이 부분도 model.addAttribute("item", deliveryService.getItemInfo(itemId)); 여기서 한번에 가져올 수 있는거죠?????

2024-09-23 05:28 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/delivery/service/DeliveryService.java
> +			deliveryFormDto.getInvoiceNumber(), deliveryFormDto.getCode(), "배송 준비 중", deliveryFormDto.getCourier());
배송 준비 중도 단순히 문자열로 하는거 보다는 이넘이나 상수로 관리하는게 좋을듯해용

2024-09-23 05:28 UTC, Yang-soeun commented on pickme/src/main/resources/mapper/DeliveryMapper.xml
> +
🍒🍒🍒

2024-09-23 05:28 UTC, Yang-soeun commented on pickme/src/main/resources/mapper/ItemLawMapper.xml
> +
🍒🍒🍒

2024-09-23 05:28 UTC, Yang-soeun commented on pickme/src/main/resources/templates/delivery/status.html
> +<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
script는 분리 해주시는게 좋을것 같아용

2024-09-23 05:28 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/controller/ItemRestController.java
> +
여기에 try-catch 대신 @RestControllerAdvice로 해결해 보시는건 어떨까용?

2024-09-23 05:30 UTC, kys0411 reviewed
고생하셨습니다👍🏻

2024-09-23 05:30 UTC, kys0411 commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +	}
뎁스는 한번만 해주세용~

2024-09-23 05:30 UTC, kys0411 commented on pickme/src/main/resources/static/css/delivery/register.css
> +    font-family: 'Arial', sans-serif;
폰트!!

2024-09-23 05:30 UTC, kys0411 commented on pickme/src/main/java/project/pickme/item/repository/ItemMapper.java
> +	String[] findImagesByItemId(long itemId);
ImageMapper에 추가!

2024-09-23 05:30 UTC, kys0411 commented on pickme/src/main/java/project/pickme/item/repository/ItemMapper.java
> +	OriginalItemDto findItemByItemId(long itemId);
나머지는 도메인명 생략해도 될거같아요~

2024-09-23 05:30 UTC, kys0411 commented on pickme/src/main/java/project/pickme/item/controller/ItemRestController.java
> +			return ResponseEntity.status(500).body("경매 수정에 실패했습니다: " + e.getMessage());
BaseResponse 써주시고 try-catch도 수정해주세용!

2024-09-23 07:08 UTC, nyeongha commented on pickme/src/main/java/project/pickme/delivery/controller/CustomsDeliveryController.java
>  	public String saveInvoiceNumber(@RequestBody DeliveryFormDto deliveryFormDto) {
마자ㅠㅠ근데 restcontroller에 requestmapping을 /tracking으로 해놨어서 그냥 controller에 어쩔수없이 넣었다가 그냥 지금 restcontroller의 requestmapping을 없애고 거기에 넣었어여!!수정한거 이따가 올리겠습니다!!

2024-09-23 07:25 UTC, nyeongha commented on pickme/src/main/resources/mapper/DeliveryMapper.xml
> +
이 함수는 삭제했습니당~!

2024-09-23 07:25 UTC, nyeongha commented on pickme/src/main/resources/mapper/ItemLawMapper.xml
> +        where Item_id = #{id}
엇 반영이 안되어있네요 고마워요!!!

2024-09-23 07:25 UTC, nyeongha commented on pickme/src/main/resources/mapper/ItemLawMapper.xml
> +
수정했습니다!!

2024-09-23 07:32 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/controller/ItemRestController.java
> +
넵 해결해보겠습니당~!

2024-09-23 07:32 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/controller/ItemRestController.java
> +			return ResponseEntity.status(500).body("경매 수정에 실패했습니다: " + e.getMessage());
넵~~!!수정할게요~!

2024-09-23 08:35 UTC, nyeongha commented on pickme/src/main/resources/static/css/delivery/register.css
> +    font-family: 'Arial', sans-serif;
수정해따~!

2024-09-24 00:41 UTC, nyeongha commented on pickme/src/main/java/project/pickme/delivery/controller/UserDeliveryController.java
> +		model.addAttribute("carrier", deliveryService.getCarrier(itemId));
넵 수정했습니당!!

2024-09-25 00:28 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/delivery/controller/DeliveryRestController.java
나중에 javadoc 주석 추가 해주세용

2024-09-25 00:28 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +		System.out.println("----");
🍒🍒🍒

2024-09-25 00:28 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +		System.out.println("==");
print 문 지워주세용 🍒🍒🍒

2024-09-25 00:28 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +		itemLawMapper.bulkInsert(laws);
👍

2024-09-25 00:28 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/delivery/controller/DeliveryRestController.java
> +	@GetMapping("/tracking/getAuthHeader")
뭔가 더 좋은 이름이으로 지을 수 있을것 같은데용

2024-09-25 00:28 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/dto/OriginalItemDto.java
> +public class OriginalItemDto {
이거는 그냥 ItemDto로 하고 업데이트만 UpdateDto로 해도 괜찮을것 같긴해용

2024-09-25 00:28 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +			laws.add(new ItemLawDto(lawId,itemDto.getItemId())); // ItemLawDto 리스트 생성
포맷터 적용 안된거 같은데용?

2024-09-25 00:28 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +		itemMapper.update(new UpdateDto(updateItemFormDto.getStartTime(), updateItemFormDto.getEndTime(), itemId));
여기에서만 updateDto가 필요한거면 updateDto사용 안하고
`itemMapper.update(updateItemFormDto, itemId));` 이런식으로 넘기면 안되나용??

2024-09-25 00:28 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +			updateItemLaws(itemId, updateItemFormDto.getLawId());
lawId 배열이면 그래도 복수형으로 해주시는게 좋을 것 같아용

2024-09-25 00:28 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +	private void updateItemLaws(long itemId, long[] lawIds) {
그러면 법은 수정하지 않고 날짜만 수정 하더라도 다 지웠다가 다시 매핑해야 하는거죠??????

2024-09-25 00:29 UTC, Yang-soeun commented
송장 등록은 모달창 !!!

2024-09-25 00:31 UTC, Yang-soeun approved these changes
수고하셨습니당

2024-09-25 00:31 UTC, Sohottoday approved these changes
고생하셨습니다!

2024-09-25 00:31 UTC, merged