Feat/177
SYSONE-PICKME/PICKME pull request #187
Opened 2024-09-25 12:35 UTC by nyeongha

## 🍀이슈 번호
- closes #177 

## ✅ 구현 내용
- [ ]  송장등록 모달로 변경
- [ ]  자바독 작성
- [ ]   컨트롤러 프린트문 제거
- [ ]   배송 시간대 포맷 변경
- [ ]   테이블 색상 변경
- [ ]   송장번호 보이는거 삭제
- [ ]   progress bar색상 변경
- [ ]   시작시간은 현재시간이후로만 설정
- [ ]   마감시간은 시작시간 이후로만 설정
- [ ]   status카드 간격 조정

## 🐸고민사항 & 기타

2024-09-25 14:57 UTC, Sohottoday reviewed
고생하셨습니다!

2024-09-25 15:25 UTC, nyeongha commented on pickme/src/main/resources/static/js/delivery/delivery.js
> +    console.log(itemId,userId);
값이 잘 전달되는지 확인하려고 로그를 찍었습니당~!

2024-09-25 15:30 UTC, nyeongha commented on pickme/src/main/resources/templates/delivery/status.html
> +        }
기존 item.css나 list.css는 아이템 목록에 맞춰져있어서 세세한부분을 맞추려다보니까 inline-grid스타일이 제일 적합해서 추가적으롤 적용했습니다~!다른걸로하면 많이깨져서요!!

2024-09-25 15:36 UTC, nyeongha commented on pickme/src/main/resources/templates/delivery/delivery.html
> +            <label for="invoiceNumber" style="margin-top: 20px">송장번호</label>
따로 빼겠습니당~!감사합니다~!!!

2024-09-26 00:09 UTC, Yang-soeun requested changes

2024-09-26 00:09 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/s3/service/S3Service.java
> -			long itemId = itemDto.getItemId();
👍👍

2024-09-26 00:09 UTC, Yang-soeun commented on pickme/src/main/resources/static/css/delivery/delivery.css
하나씩 개행 추가하기 🍒🍒

2024-09-26 00:14 UTC, kys0411 commented on pickme/src/main/java/project/pickme/item/dto/UpdateItemFormDto.java
>  }
dto 이름이 좀 헷갈리는 것 같아요~

2024-09-26 05:39 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/dto/UpdateItemFormDto.java
>  }
다음엔 req res나눠서 구현하겠습니당..!!ㅠㅠ

2024-09-26 05:39 UTC, nyeongha commented on pickme/src/main/resources/static/css/delivery/delivery.css
추가했습니당~!

2024-09-26 05:39 UTC, nyeongha commented on pickme/src/main/resources/static/js/delivery/delivery.js
>      console.log('Dropdown populated:', dropdown);
로그 지웠습니당~!

2024-09-26 05:56 UTC, Yang-soeun approved these changes

2024-09-26 05:56 UTC, Sohottoday approved these changes

2024-09-26 05:58 UTC, merged