[FEAT]: 관리자 공지 및 캠페인 관리 페이지
SYSONE-PICKME/PICKME pull request #31
Opened 2024-09-11 08:28 UTC by Sohottoday

## 🍀이슈 번호 (이슈 번호를 작성해주세요)
- Related to  #16 

## ✅ 구현 내용
- [ ] 관리자 공지 및 캠페인 목록 구현
- [ ] 관리자 공지 및 캠페인 작성 구현
- [ ] 관리자 공지 및 캠페인 수정, 삭제 구현

## 🐸고민사항 & 기타
- 공지, 캠페인 자동 분류 구현 예정
- Content 페이지 디자인 안된 상태
- 캠페인 수정 시 캠페인 페이지로 곧바로 안넘어가는 상태
- 현재 버전 기준 파일명 중복 시 강제로 덮음

2024-09-11 08:51 UTC, kys0411 requested changes
성연님 고생하셨습니다👍🏻 리뷰 읽어보시고 답글 달아주세요!

2024-09-11 08:51 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +	private FileUploadService fileUploadService;
왜 autowired 쓰셨나용?.?

2024-09-11 08:51 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +		List<NoticeDTO> listNotice = noticeService.getAllNotice();
메서드 이름은 웬만하면? 동사로 ㅎㅎ써주세요
ex `getNoticeList` `findNoticeList`,,,

2024-09-11 08:51 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +	public String updateNotice(@PathVariable("id") long id, Model model, Authentication authentication) {
/edit/{id}가 더 깔끔할것 같아용😎

2024-09-11 08:51 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +	}
캠패인은 따로 분리해도 좋을 것 같은데 어떻게 생각하시나여?.? 성연님 하고싶은대로 하시면 될 것 같아요

2024-09-11 08:51 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +		if (authentication != null && authentication.getPrincipal() instanceof CustomsDetailsImpl) {
Authentication 대신 @CurrentUser? 써주면 더 좋을 것 같습니다~! 통일감을 위해ㅎㅎ,,

2024-09-11 08:51 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +		}
이렇게 분기처리 해주는 것보다 더 좋은 방법이 있을 것 같아요!!😉

2024-09-11 08:51 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +		campaignDTO.setContent("");
Set을 여기서 해주는 이유가 있나요?.?

2024-09-11 08:51 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/domain/Notice.java
> +	}
이건 머에여?

2024-09-11 08:51 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/dto/CampaignDTO.java
> +	}
toString이 직접적으로 쓰이나요?.?

2024-09-11 08:51 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/dto/CampaignDTO.java
> +		String imageUrl, MultipartFile imageFile) {
이거는 한줄에 파라미터 하나씩 적는게 가독성이 더 좋을 것 같아용

2024-09-11 08:51 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +		}
코드가 이렇게 되니까 더더욱 분리하는게 좋을 것 같아여! 공지랑 캠페인이랑🥲

2024-09-11 08:51 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/dto/CampaignDTO.java
> +public class CampaignDTO extends NoticeDTO {
EqualsAndHashCode 쓰신 이유가 있나요?

2024-09-11 08:58 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +	@Autowired
@Autowired 를 사용하는 것 보다 @RequiredArgsConstructor를 사용하는 방법은 어떨까요?

https://backendcode.tistory.com/209

2024-09-11 08:58 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +			return "redirect:/login";
인증되지 않은 사용자인 경우에 스프링 시큐리티에서 자동으로 login 페이지로 이동하도록 되어 있습니다!

2024-09-11 08:58 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
여기서 인증객체 꺼내는 부분 부분에서 @Currentuser를 사용하면 쉽게 로그인 된 관리자 정보를 가져올 수 있습니당...!

2024-09-11 08:58 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +		campaignDTO.setContent("");
set를 사용해서 주입하는 방식은 좋지 않은 것 같습니다. 내부에서 빈내용을 가진 dto를 가지도록 하고 싶다면 dto내부에서 내용 부분을 빈걸로 생성하는게 나을것 같아요! 세터는 되도록 사용하지 않는게 좋아요!

https://mjoo1106.tistory.com/entry/Spring-Setter-vs-Builder

빌더와 세터 게터에 대해 학습해 보면 좋을 것 같아요

2024-09-11 08:58 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
전체적으로 컨트롤러에 비즈니스 로직같은 부분이 좀 보이는 것 같습니다. 컨트롤러에서는 서비스를 호출하고 반환받은 응답만 넘겨주는 정도만 있으면 좋을 것 같습니다. 로직은 서비스 쪽에서 처리하는게 더 역할에 맞는 것 같아요!!!

2024-09-11 08:58 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/domain/Notice.java
> +@Data
엔티티에는 setter를 통해 데이터가 변하는 것을 방지하기 위해서 @Data를 잘 사용하지 않습니다. @Data를 사용한 이유가 있을까요?

2024-09-11 08:58 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/dto/CampaignDTO.java
> +@EqualsAndHashCode(callSuper = true)
이거는 어떤 역할을 하는건가요??

2024-09-11 08:58 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/dto/NoticeDTO.java
> +			.customsId(notice.getCustoms().getId())
Customs customs = notice.getCustoms(); 이걸 했으면 customs.getId()를 하면 되지 않을까요?

2024-09-11 08:58 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/dto/NoticeDTO.java
> +	public Notice toEntity() {
이건 무슨 동작을 예상하고 만드신건가요????

2024-09-11 08:58 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/NoticeService.java
> +@Transactional
이 어노테이션의 의미를 알고 사용하고 있는걸까요??? select를 하는 로직들이 있는데 전체에 @Transactional을 걸면 어떤 부분이 안좋을까요??????

2024-09-11 08:58 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/NoticeService.java
전체적으로 dto에 값을 넘겨서 만들지 않고 전부 setter를 사용하셨는데 setter 보다는 파리미터로 넘겨서 값을 할당하는 것이 좋을 것 같습니다.

2024-09-12 05:00 UTC, Yang-soeun requested changes
전체적으로 코드가 엄청 깔끔해졌네용! 수고하셨습니다~ 조금만 더 힘을 내봅시당 ㅎ

2024-09-12 05:00 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/dto/NoticeDto.java
> +	public Notice toEntity() {
이런식으로 this를 사용해서 하는 방식을 선택하게 된 이유가 있을까요???궁금해🍀❓❔❓❔

2024-09-13 16:45 UTC, Sohottoday commented
안녕하십니까. 지난 2~3일간 고전하던 이슈를 해결하여 원인 공유드리고자 댓글을 작성하게 되었습니다.
목표 : controller, service 내 set으로 구현된 내용 제거
딜레이 된 이유 : DTO @NoArgsConstructor와 @AllArgsConstructor에 모두 access = AccessLevel.PROTECTED가 걸려있는 것을 집중하여 보지 못하고 이상한 곳만 지속적으로 수정하여 Customs에 null값만 반환

2024-09-14 07:37 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +			.customsId(customs.getId())
showNoticeForm에서 customsId를 가지고 있으면 NoticeDto에서도 customsId를 가질 수 있지 않나요??? 
@CurrentUser Customs customs 여기서 꺼내써야 하는 이유가 있나용? 

!currentUser, customs 그리고 위에랑 이름 통일 해주세요!!🍒

2024-09-14 07:37 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
전체적으로 Long, long을 같은 변수에도 다르게 사용하고 있는 것 같아요 통일 해주세요!🍒

2024-09-14 07:37 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +		NoticeDto updatedNoticeDto = NoticeDto.builder()
NoticeDto 내부에서 noticeDto를 받아서 updateNoticeDto를 만드는 팩토리 메서드를 만드는건 어떨까요???

2024-09-14 07:37 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +	@PostMapping("/campaign")
이 부분은 S3가 구현되면 수정 되어야 하는 부분인가요❓❓❓❓❓

2024-09-14 07:37 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +	@GetMapping("/noticeContent/{id}")
RESTFul API를 설계하기 위한 네이밍 방식 중에서 가독성을 위해 - 를 사용하는것을 추천해요!
다른 부분도 카멜케이스로 작성하신 부분은 확인 해보시고 수정 해주시면 감사하겠습니당

https://prohannah.tistory.com/156

2024-09-14 07:37 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/dto/CampaignDto.java
이 부분은 s3를 사용한다면 수정 될 부분인가요?

2024-09-14 07:37 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/NoticeService.java
> +		Notice notice = noticeMapper.selectById(id);
아이디로 찾았을때 null 인경우에 예외를 던지지 않고 null을 반환하는 이유가 있을까요?

2024-09-14 07:37 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/NoticeService.java
> +		return NoticeDto.fromEntity(noticeMapper.selectById(notice.getId()));
근데 컨트롤러에서 반환받은 dto에서 id만 사용하고 있는거 아닌가요? 사용하지 않는 정보들도 같이 반환하는 이유가 있을까요?? 아니면 사용하는 부분이 있는데 제가 놓친걸까용....?

2024-09-14 07:37 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/dto/CampaignDto.java
> +	public void setImageUrl(String imageUrl) {
setter를 직접 작성한 이유가 있나용?

2024-09-15 13:17 UTC, nyeongha reviewed
고생하셨습니당~!

2024-09-15 13:17 UTC, nyeongha commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +		model.addAttribute("customsName", customs.getName());
model.addAttribute("customs", customs);로 해서 html파일에서 name 속성에 th:text=${customs.name}
th:text=${customs.customsId} 이런식으로 가져오는게 어떨까요?

2024-09-15 13:17 UTC, nyeongha commented on pickme/src/main/java/project/pickme/user/service/CustomsService.java
> +	@PostConstruct
세관이 계속 추가될수도있는 상황이라서 이 부분은 불필요하다고 생각합니다..!
다른분들의 의견은 어떠신지..!

2024-09-15 13:17 UTC, nyeongha commented on pickme/src/main/resources/static/notice/css/noticeContent.css
> +
이부분은 다같이 붙이거나 한칸씩 띄우거나 하면 좋을것같습니당~!

2024-09-15 13:17 UTC, nyeongha commented on pickme/src/main/resources/static/notice/css/noticeContent.css
> +
이부분도~!

2024-09-15 13:17 UTC, nyeongha commented on pickme/src/main/resources/static/notice/css/noticeContent.css
> +}
여기는 엔터 치셔야할것같습니당~~!

2024-09-16 08:50 UTC, Yang-soeun requested changes

2024-09-16 08:50 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +		model.addAttribute("isCampaign", notice instanceof CampaignDto);	// 이 부분은 security 관련된 부분이 계속 에러가 발생해 AI도움을 많이 받음
어떤 부분에서 에러가 나는지는 모르겠지만 notice instanceof CampaignDto 이 부분이 필요한지는 잘 모르겠습니당 ! 다른 방식으로 해결해보시면 좋을 것 같아요~

2024-09-16 08:50 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +
공지랑 캠페인이랑 분리하는게 나을것 같아요~ 하나로 하고싶은 이유가 있을까용?

2024-09-16 08:50 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/NoticeService.java
> +			.collect(Collectors.toList());
toList()

2024-09-16 08:50 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +	private final S3FileUploadService s3FileUploadService;
민영님이 구현하신 S3Service로 변경하시는거죠???

2024-09-16 08:50 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +	public String listNotices(Model model) {
listNotices 어색해용~

2024-09-16 08:50 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/NoticeService.java
> +		if (id == null) {
예외처리를 하지 않고 null을 반환하는 이유가 있을까요?? 예외처리를 해주는게 더 좋을 것 같아용~

2024-09-16 08:50 UTC, Yang-soeun commented on pickme/src/main/resources/static/css/notice/noticeContent.css
> +
이 공백을 주는 기준이 있나요?? 위에는 다 붙어있네요~

2024-09-16 08:50 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +	public String updateNoticeOrCampaign(@PathVariable("id") Long id,
이런 부분을 타입으로 분기처리해서 굳이 하나의 요청으로 해결할 필요가 없어 보여요~ 공지랑 캠페인 분리하는게 더 좋을 것 같습니당!!!

2024-09-16 08:50 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/NoticeService.java
> +		return customsMapper.findById(customsId).get();
findById(customsId)결과가 없는데 get()으로 그냥 꺼내버리면 오류가 나지 않을까요???

`customsMapper.findById(customsId).orElseThrow(() -> new BusinessException(NOT_FOUND_COSTOMS)) ` 로 해서 없는 경우에 예외를 던지도록 해주는건 어떨까요?

2024-09-16 08:50 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +	@GetMapping("/noticeContent/{id}")
이 부분도 @RequestMapping("/customs/notice") 위에 이거랑 합쳐지면 이상할듯 해요!

2024-09-16 08:50 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/dto/NoticeDto.java
> +	private Role customsRole;
이거는 어디에 사용하려고 필요한걸까요?

2024-09-16 08:50 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/NoticeService.java
> +		noticeMapper.delete(id);
notice를 삭제할때 s3에 저장된 이미지는 삭제 안해도 괜찮을까요?

2024-09-16 08:50 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/NoticeService.java
> +			return "[Image URL: " + newImageUrl + "]";
앞에 문자열들이 필요한 이유가 궁금합니당~❓❓❓

2024-09-18 02:39 UTC, nyeongha requested changes
늦은시간인데 고생많으셨습니당ㅠㅠㅠ

2024-09-18 02:39 UTC, nyeongha commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +@Transactional(readOnly = true)
저도 조회용에서는 `@transactional(readOnly=true)`를 사용해봐야겠어요

2024-09-18 02:39 UTC, nyeongha commented on pickme/src/main/java/project/pickme/util/S3FileUploadService.java
> +
오 삭제 붙여주셨네용~!~!

2024-09-18 02:39 UTC, nyeongha commented on pickme/src/main/resources/mapper/NoticeMapper.xml
> +        SELECT
저희 소문자로 통일했습니당~! 테이블명만 앞글자 대문자!

2024-09-18 02:39 UTC, nyeongha commented on pickme/src/main/resources/mapper/NoticeMapper.xml
> +        SELECT
쿼리문은 소문자로~! 테이블 앞글자는 대문자!

2024-09-18 08:55 UTC, Yang-soeun requested changes
수고 하셨습니당 ~~ 완전 깔끔해졌네요!!!

쿼리 부분 전부 소문자로 변경해주시고!! css도 개행 통일해주세용 🍒🍒🍒
그리고 공지나 캠페인 조회할때 자기가 관리하는 것만 봐야하지 않을까요?? 다른 관세청에서 쓴 공지나 캠페인을 보여주면 안될것 같은데용?? 이 부분도 처리 해주시면 좋겠습니다~~~

그리고 Customs에 대한 정보는 CurrentUser를 활용하시면 더 간단하게 할 수 있어요!! 활용 하시는걸 추천드립니당

2024-09-18 08:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/domain/Notice.java
> +	private String type;
Enum을 활용하는것도 좋을지도~~

그리고 추가하시면 ERDCloud, notion에 쿼리문 다 변경 해주셔야 합니당~

2024-09-18 08:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/CampaignController.java
> +@RequestMapping("/customs/campaigns")
복수형으로 지으신 의미가 있을까요????

2024-09-18 08:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/mapper/NoticeMapper.java
> +	List<Notice> selectByType(@Param("type") String type);
이렇게 해줘야 하는 이유가 있나용????

2024-09-18 08:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +	private final S3FileUploadService s3FileUploadService;
민영님이 구현하신걸로 바꿔주시면 감사하겠습니다~

2024-09-18 08:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +			.collect(Collectors.toList());
toList()

2024-09-18 08:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +			return null;
null을 반환하는 것 보다는 예외 처리를 하시는게 어떨까요????

` !"CAMPAIGN".equals(notice.getType())` 타입이 캠페인인것만을 가져오고 싶다면 selectById(id) 여기서 타입이 캠페인인것만 가져오면 되지 않을까요?? 다 가져와서 검사하는 이유가 궁금합니다!

2024-09-18 08:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/NoticeService.java
> +		if (notice == null || !"NOTICE".equals(notice.getType())) {
여기서도 애초에 타입이 NOTICE 인것만 쿼리로 가져오면 되지 않을까요?

2024-09-18 08:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/NoticeService.java
> +		noticeMapper.insert(notice);
CurretUser를 파라미터로 넘겨받는다면 이런식으로 사용할 수 있을것 같아요~
```
	@Transactional
	public Long createNotice(NoticeDto noticeDto, Customs customs) {
		Notice notice = noticeDto.toEntity(customs);
```

2024-09-18 08:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/NoticeService.java
> +		Customs customs = getCustomsById(noticeDto.getCustomsId());
여기도~~~ CurrentUser를 활용하시면 좋을것 같네여~

2024-09-18 08:55 UTC, Yang-soeun commented on pickme/src/main/resources/static/css/notice/campaignContent.css
css 파일 띄어쓰기가 동일하지 않아여~~~동일하게 하나씩 다 띄워주세요!! 밑에 파일은 띄우고 여기는 다 붙어있네요!🍒🍒

2024-09-18 08:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/dto/CampaignDto.java
> +	private Role customsRole;
```
	private String customsId;
	private String customsName;
	private Role customsRole;
```
이 부분들은 어디에 필요한걸까용????

2024-09-18 08:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/dto/CampaignDto.java
> +	public Notice toEntity(Customs customs, String imageUrl) {
반환형이 Notice인데 CampaignDto 클래스에 있는게 적절한지 잘 모르겠습니다~~ Notice쪽에 있어야 할 것 같은데용~

2024-09-18 08:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +		List<NoticeDto> notices = noticeService.getAllNotices();
근데~~ 세관별로 자기가 작성한 공지만 볼 수 있어야 하는거 아닌가여??????? 다른 세관 공지도 볼 수 있나용?

2024-09-18 08:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/CampaignController.java
> +		campaignDto = campaignDto.withId(id);
setter를 쓰지 않으려고 아이디 하나만 다른데 똑같은 내용을 withId로 다시 생성하고 있는것 같은뎅 
이런 경우에 setter써도 괜찮을것 같아요! 근데 그렇게 하지 않고

`campaignService.updateCampaign(campaignDto, id);` 로 해도 되지 않을까요????

성연님의 코드를 보면 메소드의 파라미터가 전부 1개이던뎅?? 이유가 있으실까요(?) 궁금합니당

2024-09-18 08:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +
```
		Customs customs = getCustomsById(campaignDto.getCustomsId());
		String imageUrl = null;
		if (campaignDto.getImageFile() != null && !campaignDto.getImageFile().isEmpty()) {
			imageUrl = s3FileUploadService.uploadFile(campaignDto.getImageFile());
		}
```
createCampaign 랑 updateCampaign에서 동일한 로직은 메소드로 분리해서 사용하는 방법도 좋을것 같아용		Customs customs = getCustomsById(campaignDto.getCustomsId());
		String imageUrl = null;
		if (campaignDto.getImageFile() != null && !campaignDto.getImageFile().isEmpty()) {
			imageUrl = s3FileUploadService.uploadFile(campaignDto.getImageFile());
		}
```
createCampaign 랑 updateCampaign에서 동일한 로직은 메소드로 분리해서 사용하는 방법도 좋을것 같아용

2024-09-18 08:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +		noticeMapper.delete(id);
S3에 올라간 이미지도 지워주셔야 하지 않을까요?

2024-09-18 08:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +		Long noticeId = noticeService.createNotice(noticeDto);
다른곳은 id인데 여기만 noticeId네요 이런것도 통일해주면 좋지 않을까용?

2024-09-18 08:55 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +	@GetMapping("/delete/{id}")
AJAX로 변경한다면 @GetMapping("/delete/{id}") 이 부분에 행위대한 부분("/delete)은 @DeleteMapping으로 메소드로 표현 해주셔야 합니다~~~

2024-09-18 09:48 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/controller/CampaignController.java
> +		campaignDto = campaignDto.withId(id);
set을 쓰면 안되나? 하는 강박때문에 자꾸 돌고돌아서 저런식으로 하였고 아직은 명확하게 알지 못해도 어디서 보고 듣고 한 부분만 반복 반복해서 사용하다보니 제시해주신 내용대로 더 간단하게 구현하는 방법까지는 생각이 도달하지 못하고 있습니다 😥😥

2024-09-18 09:48 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +	@GetMapping("/delete/{id}")
넵! 지난번에 찾아봤을 때 말씀해주신대로 하는게 좋다고 나와있어 따로 적어두었습니다! 다만 아직 @Get이랑 @Delete는 뭐가 다른건데? 를 제대로 보지는 못해서 보류중이었습니다! 적용해볼게요!

2024-09-18 09:48 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +
넵! extract로 한개 만들어서 사용하겠습니다!

2024-09-18 09:48 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/service/CampaignService.java
> +		noticeMapper.delete(id);
제가 만든 S3FileUploadService에서
`public void deleteFile(String fileName) {
		amazonS3Client.deleteObject(s3Config.getBucket(), fileName);
	}`
로 구현해두었는데 민영님 코드로 바꾸면 따로 구현하도록 하겠습니다!

2024-09-18 09:57 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/notice/mapper/NoticeMapper.java
> +	List<Notice> selectByType(@Param("type") String type);
ㅋㅋㅋㅋㅋㅋㅋㅋ 고생하셨습니당

2024-09-23 04:52 UTC, closed without merging