[FEAT]: 공매품 등록 구현(이미지 제외)
SYSONE-PICKME/PICKME pull request #32
Opened 2024-09-11 09:24 UTC by nyeongha

## 🍀이슈 번호 (이슈 번호를 작성해주세요)
closes #12 

## ✅ 구현 내용
- [ ] 공매품 등록(이미지 제외)

## 🐸고민사항 & 기타

2024-09-11 09:42 UTC, Yang-soeun requested changes

2024-09-11 09:42 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/customs/repository/CustomsRepository.java
> +
공백 신경 써주세용~

2024-09-11 09:42 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/customs/service/CustomsSevice.java
> +@RequiredArgsConstructor
@RequiredArgsConstructor랑 @Autowired를 같이 써야할까요...? 둘에 대해 공부 해보시면 좋을것 같아요~~

2024-09-11 09:42 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/ItemController.java
> +@RequiredArgsConstructor
이것만 쓰시고 private final로 하는게 좋을 것 같아요~

2024-09-11 09:42 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/ItemController.java
> +		LocalDateTime start = LocalDateTime.of(itemFormDTO.getStartDate(), itemFormDTO.getStartTime());
이런 서비스 로직은 서비스 내부에서 구현하는게 좋을 것 같아요! 컨트롤러의 역할에 맞지 않는 것 같습니다아

2024-09-11 09:42 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/ItemController.java
> +		// if (files == null || files.length == 0) {
사용하지 않는 주석은 지워주세요

2024-09-11 09:42 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/domain/ImageDTO.java
> +	private Long item_id;
자바는 카멜케이스로 변수 이름 지어주세요

2024-09-11 09:42 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/domain/ItemFormDTO.java
> +
이 공백은 ,,,?

2024-09-11 09:42 UTC, Yang-soeun commented on pickme/src/test/java/project/pickme/item/service/ItemServiceTest.java
> +	// @Test
사용안하는 주석! 지워주세요!

2024-09-11 09:42 UTC, Yang-soeun commented on pickme/src/main/resources/mapper/CustomsMapper.xml
파일 끝 개행 문자!

2024-09-11 09:42 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/domain/Item.java
> +	private String category;
Enum으로 하는게 좋을 것 같아요!

2024-09-11 09:42 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/domain/LawDTO.java
> +	private int id;
아이디가 int인가요?

2024-09-11 09:46 UTC, kys0411 requested changes
민영님 고생하셨어요~👍🏻😉 전체적으로 불필요한 코드가 너무 많은 거같아여ㅎㅎ 다음부터는 신경써서 커밋해주세요~~

2024-09-11 09:46 UTC, kys0411 commented on pickme/src/main/java/project/pickme/item/domain/ItemFormDTO.java
> +
😉

2024-09-11 09:46 UTC, kys0411 commented on pickme/src/main/java/project/pickme/item/ItemController.java
> +		// }
😉

2024-09-11 09:46 UTC, kys0411 commented on pickme/src/main/java/project/pickme/customs/service/CustomsSevice.java
> +
😉

2024-09-11 09:46 UTC, kys0411 commented on pickme/src/main/java/project/pickme/customs/repository/CustomsRepository.java
> +
😉

2024-09-11 09:46 UTC, kys0411 commented on pickme/src/test/java/project/pickme/item/service/ItemServiceTest.java
> +}
주석 제거해주시고 사용안하는 메서드 삭제하는게 좋을 것 같아요~😉

2024-09-11 09:46 UTC, kys0411 commented on pickme/src/main/java/project/pickme/item/domain/ItemFormDTO.java
> +@Setter
이유없는 Setter~.~

2024-09-11 14:55 UTC, nyeongha reviewed
공백 추가하고 사용하지않는 improt삭제했습니다!

2024-09-11 14:55 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/ItemController.java
> +@RequiredArgsConstructor
수정했습니당~~!

2024-09-11 14:55 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/domain/ImageDTO.java
> +	private Long item_id;
넵 이것도 따로 수정해서 push하겠습니당~!

2024-09-11 14:55 UTC, nyeongha commented on pickme/src/test/java/project/pickme/item/service/ItemServiceTest.java
> +}
넹 파일을 일단 삭제할게요!!

2024-09-11 15:00 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/domain/Item.java
> +	private String category;
수정했습니당~!

2024-09-12 02:24 UTC, nyeongha reviewed
[FIX]: 공백제거

2024-09-12 02:33 UTC, nyeongha reviewed
[FIX]: 공백제거

2024-09-12 04:28 UTC, Yang-soeun requested changes
전체적으로 Mapper.xml 파일의 테이블 이름을 첫 글자를 대문자로 변경 해주셔야 할 것 같아요~~~🍒

2024-09-12 04:28 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/dto/ImageDto.java
> +	private Long item_id;
itemId 🍒

2024-09-12 04:28 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/service/LawService.java
> +	}
return lawMapper.findAllLaws(); 이렇게 하는 방법은 어떨까요???

2024-09-12 04:28 UTC, Yang-soeun commented on pickme/src/main/resources/mapper/ItemMapper.xml
> +        from item
이것드 ! 테이블 이름 Item

2024-09-12 04:28 UTC, Yang-soeun commented on pickme/src/main/resources/static/css/item.css
> +
🍒

2024-09-12 04:28 UTC, Yang-soeun commented on pickme/src/main/resources/static/css/item.css
> +
🍒

2024-09-12 04:28 UTC, Yang-soeun commented on pickme/src/test/java/project/pickme/customs/service/CustomsSeviceTest.java
> +	@Test
어떤 동작을 테스트 하는지 알기 쉽게 @DisplayName을 사용해주시면 좋을것 같아요!

2024-09-12 04:28 UTC, Yang-soeun commented on pickme/src/test/java/project/pickme/customs/service/CustomsSeviceTest.java
> +		Customs result= customsService.findById("kimpo");
findById를 테스트 하고 싶은거라면 servie를 테스트 하는것 보다 mapper를 테스트 하는게 목적에 더 맞을 것 같습니당

2024-09-12 04:28 UTC, Yang-soeun commented on pickme/src/test/java/project/pickme/item/service/LawServiceTest.java
> +		System.out.println(laws.size());
테스트 코드 검증은 출력 보다는 Assertions.assertThat 을 사용해서 테스트 해주시는게 좋을 것 같습니당

2024-09-12 04:28 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +	public void update(ItemDto item) {
실제로 구현되지 않은 메서드 들은 삭제해주세용~~

2024-09-12 04:28 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +	public void delete(Long id) {
🍒

2024-09-12 04:28 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/controller/ItemController.java
> +		return "create-item";
얘네를 서비스에서 한번에 반환하는 dto를 만드는건 어떨까요? 서비스 내부에 로직을 보면 단순히 mapper들만 호출하고 있어서 걔네를 한번에 하는 방법은 어떨까 의견을 내봅니당~ 
그리고 		`model.addAttribute("item", new ItemFormDto()); 이 부분은 @ModelAttribute ItemFormDto itemFormDto `이런 식으로 사용을 하면 될 것 같아요!

2024-09-12 05:10 UTC, nyeongha reviewed
수정했어요~!

2024-09-13 01:55 UTC, closed without merging