[FEAT]: 이미지 제외하고 공매품 등록 폼구현
SYSONE-PICKME/PICKME pull request #42
Opened 2024-09-13 01:54 UTC by nyeongha

## 🍀이슈 번호
- closes #36

## ✅ 구현 내용
- [x] 이미지 제외하고 구현

## 🐸고민사항 & 기타

2024-09-13 02:13 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/controller/ItemController.java
> +		return "item/create-item.html";
뒤에 html은 작성하지 않아용~

2024-09-13 02:13 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/controller/ItemController.java
> +		model.addAttribute("item", new ItemFormDto());
@ModelAttribute ItemFormDto item를 사용해서 파라미터로 전달한다면 더 간결할 것 같아요!

2024-09-13 02:13 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/domain/Category.java
> +	Category(int code, String name) {
어노테이션을 사용하는 방법도 깔끔하고 좋을 것 같아용

2024-09-13 02:13 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/dto/ItemFormDto.java
> +@Setter
setter를 어디에서 사용하고 있나요?

2024-09-13 02:14 UTC, Yang-soeun reviewed
코드가 엄청 깔끔해졌네용~ 수고하셨습니당 ⭐⭐

2024-09-13 02:18 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/dto/ItemFormDto.java
> +	private int law;
폼에서 law를 선택해서 서버로 들어오는 값이 law_id(int)입니당!

2024-09-13 02:18 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/controller/ItemController.java
> +		return "item/create-item.html";
수정하겠습니당~!

2024-09-13 02:19 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/controller/ItemController.java
> +		model.addAttribute("item", new ItemFormDto());
저번에 말해줘서 해봤는데 잘안돼서 기존꺼로 했습니다ㅠㅠ다시 시도해보겠습니다~!

2024-09-13 02:19 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/domain/Category.java
> +	Category(int code, String name) {
수정하겠습니당~!

2024-09-13 02:20 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/dto/ItemFormDto.java
> +	private int law;
그러면 lawId로 지어주는게 좋을 것 같아요!

2024-09-13 02:21 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/controller/ItemController.java
> +		model.addAttribute("item", new ItemFormDto());
넹 전달하는 이름이랑 잘 확인하시면 될 것 같아요! 안돼면 이렇게 하셔도 문제는 없습니당~~

2024-09-13 02:24 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/dto/ItemFormDto.java
> +@Setter
form에서 name이랑 itemFormDto의 속성들과 매핑?시킬때 사용합니당!
그래서 setter를 사용안하면 값이 안가져와져요

2024-09-13 02:33 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/dto/ItemDto.java
> +	private Long price;
우왕 또 배워가네요~!!넘 고마워요!

2024-09-13 02:33 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/dto/ItemFormDto.java
> +	private int law;
수정하겠습니당~!!

2024-09-14 02:18 UTC, kys0411 requested changes
민영님 고생하셨습니다~!😉👍🏻

2024-09-14 02:18 UTC, kys0411 commented on pickme/build.gradle
> +    mavenCentral()
이 파일 옮길때 뎁스가 이상해진거같아요! 원래대로 하는게 좋을 것 같습니당

2024-09-14 02:18 UTC, kys0411 commented on pickme/src/main/java/project/pickme/item/controller/ItemController.java
> +		IOException {
원래 이렇게 throws랑 Exception이 떨어져있나요? 아니면 여기서 그렇게 보이는건가🥲

2024-09-14 02:18 UTC, kys0411 commented on pickme/src/main/resources/mapper/ItemMapper.xml
> +        VALUES (#{name}, #{code}, #{type}, #{price}, #{startTime}, #{endTime}, #{status}, #{customsId})
sql문은 소문자로 하기로 했죠?😉

2024-09-14 03:07 UTC, nyeongha commented on pickme/build.gradle
> +    mavenCentral()
엇 혹시 이거 naver포매팅으로 변경한건데 다시 바꿀까요??

2024-09-14 03:08 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/controller/ItemController.java
> +		IOException {
엇 이건 수정할겡!!고마오~!!

2024-09-14 03:14 UTC, nyeongha commented on pickme/src/main/resources/mapper/ItemMapper.xml
> +        VALUES (#{name}, #{code}, #{type}, #{price}, #{startTime}, #{endTime}, #{status}, #{customsId})
이것도 수정했당ㅎㅎ꼼꼼하게 봐줘서 넘 고마웡👍😊

2024-09-14 03:48 UTC, nyeongha commented on pickme/src/main/resources/mapper/ItemMapper.xml
> +        VALUES (#{name}, #{code}, #{type}, #{price}, #{startTime}, #{endTime}, #{status}, #{customsId})
이거 수정하고 push했는데 왜 반영이 안되지..?

2024-09-14 03:51 UTC, nyeongha commented on pickme/src/main/resources/mapper/ItemMapper.xml
> +        VALUES (#{name}, #{code}, #{type}, #{price}, #{startTime}, #{endTime}, #{status}, #{customsId})
아 깃허브 feat/36들어가서 보니까 반영되어있다 여기에는 안보이네ㅠㅠ

2024-09-14 10:41 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +			sequence++;
이 부분에 seq를 따로 선언한 이유가 있을까요?

2024-09-14 10:41 UTC, Sohottoday approved these changes
고생많으셨습니다!

2024-09-14 13:59 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +			sequence++;
넹 이부분은 클라이언트 통해서 받은 이미지 순서대로 순서를 지정하기 위해서 seq변수를 선언했습니당~!

2024-09-14 14:20 UTC, kys0411 approved these changes
고생하셨어요 민영님!🍀😎

2024-09-14 14:52 UTC, merged

2024-09-15 06:31 UTC, Yang-soeun reviewed
수고 하셨습니당 ~ 이미지 처리하는 부분은 따로 ImageService나 S3서비스로 분리하고 ItemService는 따로 구현하는게 좋을 것 같아요~ 다른 서비스에서도 이미지 저장 로직을 사용해야하니깐용

2024-09-15 06:31 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
이미지 저장하는 부분은 따로 서비스로 분리하는게 좋을 것 같아요 이미지 저장하는건 아이템 등록할때만 쓰이는건 아니니깐요!

2024-09-15 06:31 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +	public void save(ItemFormDto itemFormDto, MultipartFile[] files, @CurrentUser Customs customs) throws IOException {
@CurrentUser는  컨트롤러를 제외하고는 파라미터로 넘겨 받아서 사용해주세요!

2024-09-15 06:31 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +			throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "이미지 업로드에 실패했습니다.");
예외 처리는 common package 안에 있는 예외를 이용해서 던져주세용~

2024-09-15 06:31 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/dto/ItemDto.java
> +	private long itemId;
여기서만 long인 이유는?

2024-09-15 06:31 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/dto/LawDto.java
전체적으로 Long, long을 이유 없이 다르게 사용하고 있는 것 같아요 통일해주세요~🍒⭐

2024-09-15 06:31 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +@Service
@Component
@Service

이거 두개를 다 해줘야 하는 이유가 있나용?

2024-09-15 07:20 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
그럼 혹시 S3Service를 ItemService에서 불러와서 사용해도되나요...?그거때문에 합쳤거든요,,ㅠㅠㅠ아니면 controller에서 다른 서비스를 받아오는게 가능한지...

2024-09-15 07:22 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +			throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "이미지 업로드에 실패했습니다.");
넵!!

2024-09-15 07:43 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
방금 찾아봤는데 순환이 생기는거 아니면 의존성이 생기는게 아쉽긴해도 어쩔수없는거인가봐요,,,,일단 수정하겠습니다!!

2024-09-15 07:44 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +	public void save(ItemFormDto itemFormDto, MultipartFile[] files, @CurrentUser Customs customs) throws IOException {
수정하겠습니당~!

2024-09-15 07:46 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +@Service
conponent는 삭제하겠습니당!!

2024-09-15 07:47 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
혹시 수정은 feat/36가서 하나요?아니면 pull받고 작업중인 새브랜치에서 수정할까요??

2024-09-15 10:27 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/dto/LawDto.java
모두 long으로 하겠습니당~!