[FEAT]: 관리자 메인 및 헤더 구
SYSONE-PICKME/PICKME pull request #45
Opened 2024-09-14 05:04 UTC by Sohottoday

## 🍀이슈 번호 
- closes #33 

## ✅ 구현 내용
- [ ] 관리자 메인 화면 구현
- [ ] 관리자 공통 헤더 구현

## 🐸고민사항 & 기타
- 문의사항 및 사용자 관리 페이지 없을 경우 대체 항목 필요

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/ba2ec493-93ad-4ed4-9410-a2f8da5aadeb">

2024-09-14 08:04 UTC, kys0411 requested changes
성연님 저번 PR 피드백이랑 겹치는게 있다면 resolve 해주시면 됩니다~! 고생하셨습니다

2024-09-14 08:04 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/dto/CampaignDto.java
> +			imageUrl = content.substring(index + 12, content.length() - 1);
12의 의미는 뭐에요?

2024-09-14 08:04 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/service/NoticeService.java
> +		}
null을 직접적으로 리턴하는 코드는 줄이시는게 좋을 것 같습니다~!
https://dundung.tistory.com/187

2024-09-15 07:53 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +	@GetMapping("/newNotice")
수정 완료!

2024-09-15 07:59 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +	@GetMapping("/newCampaign")
수정, 삭제가 하나로 관리하고 있어 저렇게 작업하였는데 어떤 방향이 더 나은지 조언 주시면 감사하겠습니다!

2024-09-15 08:15 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +		String imageUrl = null;
캠페인 게시판에서 제목만 쓰고 이미지 첨부 없이 등록하기를 했을 때 등록이 되어버리는 경우가 있어서 해당 문제를 해결해보려고 했었습니다!

2024-09-15 08:15 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/dto/CampaignDto.java
> +public class CampaignDto extends NoticeDto {
이 부분은 과거 dto에대해 잘 알지 못할때 단순하게 코드가 재사용되는게 많으니 상속받아야징 해서 이런 방식을 택한 것이었고 이후에 access 문제를 해결할 때 시도하던 resquest, response로 dto를 나누면서 상속 없이 진행 할 예정입니다! 🤐🤐🤐🤐

2024-09-15 08:15 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/dto/CampaignDto.java
> +		String imageUrl, MultipartFile imageFile) {
수정 완료!

2024-09-15 08:15 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/dto/CampaignDto.java
> +			imageUrl = content.substring(index + 12, content.length() - 1);
[Image URL:  <-- 이거 잘라내겠다는 의미입니다!

2024-09-15 08:15 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/notice/dto/NoticeDto.java
> +@Builder
넵! 아직은 지저분하게 코드가 구현되어 있어 하나둘씩 다 연계되어 있는데 차차 개선해나가면서 최소화시켜보겠습니다! 😢😢

2024-09-15 08:15 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/user/domain/Customs.java
> +		return new Customs(id, "", Role.ROLE_ADMIN, name, "");
과거 버전 복구시키면서 꼬인 상태입니다 😢😢🍒🍒

2024-09-15 08:15 UTC, Sohottoday commented on pickme/src/main/java/project/pickme/util/FileUploadService.java
> +			System.err.println("파일 저장 중 오류 발생: " + e.getMessage());
S3로 변경하면서 전부 수정 될 예정입니다!

2024-09-15 08:15 UTC, Sohottoday commented on pickme/src/main/resources/mapper/NoticeMapper.xml
> +        order by notice_id desc;
조금 더 가독성 있게 수정해보겠습니다!

2024-09-15 08:15 UTC, Sohottoday commented on pickme/src/main/resources/mapper/NoticeMapper.xml
> +        </delete>
🍒🍒🤐🤐

2024-09-15 12:19 UTC, kys0411 commented on pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
> +	@GetMapping("/newCampaign")
어떤 수정 삭제용?

2024-09-19 08:12 UTC, closed without merging