[FEAT]: 내 낙찰 목록 조회(배송 현황 조회)
SYSONE-PICKME/PICKME pull request #47
Opened 2024-09-14 08:07 UTC by nyeongha

## 🍀이슈 번호
- closes #44

## ✅ 구현 내용
- [x] 내 낙찰 목록 가져올 기능 구현
- [x] 내 낙찰 목록 화면 구현

## 🐸고민사항 & 기타

2024-09-14 08:15 UTC, Yang-soeun requested changes
컨트롤러 쪽에 코드 포맷터 적용해주세용~ 수고하셨습니당🍀

2024-09-14 08:15 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/bid/controller/BidController.java
> +	@GetMapping("/successfulBidList")
https://prohannah.tistory.com/156

api 네이밍 작성하는 법 공부 해보시면 좋을 것 같아용!

2024-09-14 08:15 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/bid/controller/BidController.java
> +	public String successfulBidList(@CurrentUser User user,Model model) {
🍒 포맷터 적용 해주시면 감사하겠습니당

2024-09-14 08:15 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/bid/service/BidService.java
> +	public List<SuccessfulBidDto> findMySuccessfulBid(@CurrentUser User user) {
@CurrentUser User user 여기서는 컨트롤러에서 넘겨줬으니 그냥 User user로 사용하시면 됩니다아

2024-09-14 08:15 UTC, Yang-soeun commented on pickme/src/main/resources/mapper/BidMapper.xml
> +          and img.seq=0;
seq에 0도 있나용????

2024-09-14 08:18 UTC, nyeongha commented on pickme/src/main/resources/mapper/BidMapper.xml
> +          and img.seq=0;
넵 0부터 시작하도록 했어요!

2024-09-14 08:18 UTC, nyeongha commented on pickme/src/main/java/project/pickme/bid/service/BidService.java
> +	public List<SuccessfulBidDto> findMySuccessfulBid(@CurrentUser User user) {
수정하겠습니당!!

2024-09-14 08:19 UTC, nyeongha commented on pickme/src/main/java/project/pickme/bid/controller/BidController.java
> +	public String successfulBidList(@CurrentUser User user,Model model) {
엇 넵!

2024-09-14 08:19 UTC, nyeongha commented on pickme/src/main/java/project/pickme/bid/controller/BidController.java
> +	@GetMapping("/successfulBidList")
감사합니당!!~!공부하고 다시 수정할게용~!

2024-09-14 14:28 UTC, kys0411 commented on pickme/src/main/resources/mapper/BidMapper.xml
> +          and img.seq=0;
@nyeongha 앗 그럼 제 코드도 수정이 필요하겠네요,,🥲

2024-09-14 14:29 UTC, kys0411 commented on pickme/src/main/resources/mapper/BidMapper.xml
> +        select i.item_id as itemNum,i.name as itemName,c.name as customsName,b.price as price,img.url as imgUrl
공백이 없으니까 보기 불편한것같아용 ㅜ

2024-09-14 14:30 UTC, kys0411 approved these changes
민영님 고생하셨습니다~ 소은님이 거의다 작성해주셨네용👍🏻 sql 쪽만 봐주시면 좋을 것 같아요~

2024-09-14 15:02 UTC, nyeongha commented on pickme/src/main/resources/mapper/BidMapper.xml
> +        select i.item_id as itemNum,i.name as itemName,c.name as customsName,b.price as price,img.url as imgUrl
수정했습니당~!

2024-09-15 06:41 UTC, Yang-soeun approved these changes
수고 했어용~
@GetMapping("/successful-bid-list")

이 부분은 조금 더 간결하면 좋을 것 같긴해요~~~~

2024-09-15 06:46 UTC, merged