[FEAT]: 송장 등록 여부와 입찰 성공 여부에 따라 버튼 지정 및 경로 지정
SYSONE-PICKME/PICKME pull request #66
Opened 2024-09-17 07:11 UTC by nyeongha

## 🍀이슈 번호
- closes #60

## ✅ 구현 내용
- [x] 송장 등록 여부와 입찰 성공 여부에 따라 버튼 지정
- [x] 버튼에 따라 경로 설정

## 🐸고민사항 & 기타

2024-09-17 08:02 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
이 메소드는 현재 어디에 사용되고 있을까요???

2024-09-17 08:46 UTC, nyeongha commented on pickme/src/main/java/project/pickme/delivery/repository/DeliveryMapper.java
> +	List<Long> registeredInvoiceItemId();
맞아여! 그럼 앞에 get을 붙이는게 좋다는 거죠??

2024-09-17 08:50 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +		List<ItemDto> itemList = itemMapper.findItemsByCustomsId(customsId);
감사합니당~~!!복수형으로 변경하겠습니당

2024-09-17 08:53 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
<img width="213" alt="스크린샷 2024-09-17 오후 5 52 06" src="https://github.com/user-attachments/assets/2c1383b1-cbb4-4979-975f-7e259878d39b">
등록폼에 법규목록 보여줄때 사용합니당~!

2024-09-18 01:24 UTC, Sohottoday reviewed
고생하셨습니다!

2024-09-18 01:24 UTC, Sohottoday commented on pickme/src/main/resources/mapper/DeliveryMapper.xml
> +        where invoice_number is not null;
❓구분을 위해 이렇게 되어있는 건가요?

2024-09-18 09:24 UTC, Yang-soeun requested changes

2024-09-18 09:24 UTC, Yang-soeun commented on pickme/src/main/resources/mapper/BidMapper.xml
> +        SELECT b.item_id    as itemNum,
소문자~~ 🍒🍒🍒

2024-09-18 09:24 UTC, Yang-soeun commented on pickme/src/main/resources/mapper/ItemMapper.xml
> +                 left join (SELECT item_id, MAX(bid_time), is_success
🍒🍒🍒

2024-09-18 09:24 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/bid/dto/SuccessfulBidDto.java
>  	private String itemNum;
private String itemNum; 어떤걸 의미하는건가요?

2024-09-18 09:24 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/controller/ItemController.java
>  	Customs customs) throws IOException {
한줄로 적는게 더 깔끔할거 같아용

2024-09-18 09:24 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/dto/ItemDto.java
> +	private Boolean isSuccess;
참조 타입을 사용하는 이유가 있으실까용?

2024-09-18 09:24 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +	// 등록한 경매 전체 조회 및 낙찰된 물품은 마감처리
낙찰된 물품을 마감처리 하는게 아니라 마감시간이 지난 물품을 마감처리 해야하지 않을까요????

2024-09-18 09:24 UTC, Yang-soeun commented on pickme/src/main/resources/mapper/BidMapper.xml
> +                            GROUP BY item_id) b
🍒🍒🍒🍒

2024-09-18 09:24 UTC, Yang-soeun commented on pickme/src/main/resources/mapper/ItemMapper.xml
> +        order by isSuccess;
동일한 isSuccess일때도 정렬 기준이 있어야 할 것 같아용

2024-09-18 09:24 UTC, Yang-soeun commented on pickme/src/main/resources/mapper/ItemMapper.xml
> +    <!--is_success를 통해 마감 여부 지정-->
is_success가 아니라 status가 CLOSED 인걸로 마감 여부를 확인하는게 쿼리가 조금 더 간단하고 상황적으로도 맞을거 같아요~

2024-09-18 09:24 UTC, Yang-soeun commented on pickme/src/main/resources/static/js/item/item.js
> +
여기는 비동기로 하는 부분인가요?? 비동기는 Ajax로 통일 해주세용

2024-09-18 09:58 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/dto/ItemDto.java
> +	private Boolean isSuccess;
엇 제 무지입니다,,,,Boolean도 참조타입 원시타입 나뉘는지 첨알았네요!수정하겠습니당

2024-09-18 09:58 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/service/ItemService.java
> +	// 등록한 경매 전체 조회 및 낙찰된 물품은 마감처리
넵 수정했습니다!

2024-09-18 10:00 UTC, nyeongha commented on pickme/src/main/resources/mapper/ItemMapper.xml
> +        order by isSuccess;
제가 아까 push한거 다시 봐주시면 감사하겠습니다! sql문 완전 갈아엎었어요!

2024-09-18 10:01 UTC, nyeongha commented on pickme/src/main/resources/mapper/ItemMapper.xml
> +    <!--is_success를 통해 마감 여부 지정-->
넵 저두 아까 깨닫구 변경했습니당!

2024-09-18 23:57 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/delivery/controller/DeliveryController.java
> +	@GetMapping("/admin")
어떤 동작을 하는 url인지 의미가 잘 전달이 안되는것 같아용

2024-09-18 23:57 UTC, Yang-soeun commented on pickme/src/main/java/project/pickme/item/dto/ItemDto.java
> +	private int isSuccess;
int로 한 이유가 궁금해요~

2024-09-18 23:57 UTC, Yang-soeun commented on pickme/src/main/resources/mapper/BidMapper.xml
> +    <!--내 낙찰 정보 조회-->
내 낙찰 정보를 조회하는데 이런 쿼리가 필요한가용???

이해가 잘 안가서 그러는데 어떻게 동작하는지 설명해주실 수 있나용?????

2024-09-18 23:57 UTC, Yang-soeun commented on pickme/src/main/resources/mapper/DeliveryMapper.xml
쿼리에서 필요한 정보만을 가져오고 있는게 맞나요????? 전체적으로 쿼리한번 설명 해주시면 감사하겠습니당~

2024-09-19 06:40 UTC, nyeongha commented on pickme/src/main/java/project/pickme/delivery/controller/DeliveryController.java
> +	@GetMapping("/admin")
/delivery로만 하기!

2024-09-19 06:40 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/dto/ItemDto.java
> +	private int isSuccess;
boolean으로 변경!

2024-09-19 16:07 UTC, nyeongha commented on pickme/src/main/java/project/pickme/item/dto/ItemDto.java
> +	private int isSuccess;
이건 삭제했습니당~!

2024-09-19 16:08 UTC, nyeongha commented on pickme/src/main/resources/mapper/BidMapper.xml
> +    <!--내 낙찰 정보 조회-->
피드백 후 삭제했습니다~!

2024-09-19 23:52 UTC, closed without merging